# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abt.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(268, 398)
        MainWindow.setMinimumSize(QtCore.QSize(268, 398))
        MainWindow.setMaximumSize(QtCore.QSize(268, 398))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStatusTip("")
        MainWindow.setAccessibleName("")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ErMax = QtWidgets.QLabel(self.centralwidget)
        self.ErMax.setGeometry(QtCore.QRect(-80, 0, 296, 161))
        self.ErMax.setText("")
        self.ErMax.setPixmap(QtGui.QPixmap("Image2.png"))
        self.ErMax.setScaledContents(True)
        self.ErMax.setAlignment(QtCore.Qt.AlignCenter)
        self.ErMax.setObjectName("ErMax")
        self.vno = QtWidgets.QLabel(self.centralwidget)
        self.vno.setGeometry(QtCore.QRect(84, 341, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.vno.setFont(font)
        self.vno.setAlignment(QtCore.Qt.AlignCenter)
        self.vno.setObjectName("vno")
        self.SoftText = QtWidgets.QLabel(self.centralwidget)
        self.SoftText.setGeometry(QtCore.QRect(125, 20, 106, 76))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.SoftText.setFont(font)
        self.SoftText.setObjectName("SoftText")
        self.HardText = QtWidgets.QLabel(self.centralwidget)
        self.HardText.setGeometry(QtCore.QRect(135, 70, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.HardText.setFont(font)
        self.HardText.setObjectName("HardText")
        self.about = QtWidgets.QLabel(self.centralwidget)
        self.about.setGeometry(QtCore.QRect(50, 5, 141, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.about.setFont(font)
        self.about.setAlignment(QtCore.Qt.AlignCenter)
        self.about.setObjectName("about")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 120, 226, 226))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "About ErMax-pic2ascii"))
        self.vno.setText(_translate("MainWindow", "v.1.7.21.9"))
        self.SoftText.setText(_translate("MainWindow", "ErMax.Inc"))
        self.HardText.setText(_translate("MainWindow", "Software at its finest"))
        self.about.setText(_translate("MainWindow", "About pic2ascii:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">pic2ascii is an open source app run by the ErMax.Inc comunity. Pic2ascii can turn regular pictures into ascii characters with detail (or no detail) and </span><span style=\" font-size:9pt; color:#ff0000;\">c</span><span style=\" font-size:9pt; color:#ffaa00;\">o</span><span style=\" font-size:9pt; color:#a2a200;\">l</span><span style=\" font-size:9pt; color:#00aa00;\">o</span><span style=\" font-size:9pt; color:#0055ff;\">r</span><span style=\" font-size:9pt; color:#aa00ff;\">. </span><span style=\" font-size:9pt; color:#000000;\">You can also control various peramitars like the scale factor of the characters, the font and even the characters themself. At the moment, pic2ascii only suports the .jpg as an input format and both jpg and .png as an output format but that may change in the future. For now please enjoy the comunity\'s software.</span></p></body></html>"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
